### ISSUE TITLE
How to ensure HTML popup scrolls?

### ISSUE THREAD

**Issue by karam94** [Toddish/Popup#12]
Hi,

I'm currently using popup with the inline HTML option but on smaller resolutions the contents may be too tall for certain resolutions so I require them to be able to scroll. However scrolling at the moment only scrolls the actual site in the background behind the popup. How can I change this?

Thanks

**Comment by karam94** [comment]
Fine now, sorted it.
Set popup_cont to position absolute to get what I was looking for.
Can't believe it took me that long to find the solution.

**Comment by natyarantes** [comment]
Hi!

I've set this class as absolute, as you said, but all I got was the top to show on the right place. If I set height, it cuts the background, but the text is still big and it won't scroll instead. Any sugestions?
