### ISSUE TITLE
default inline issue

### ISSUE THREAD

**Issue by dustindong** [Toddish/Popup#13]
hi, i love this js script, and thank you so much for creating it. if i use default inline for popup js, if the container has too much content, its not scrollable and will only show partial content. is there any way where the container can be scrollable inside popup.js?

**Comment by Toddish** [comment]
Hey,

You could do a couple of things off the top of my head:

+ Add overlfow-y: scroll to .popup_back
+ Add a max-height and overflow-y:scroll to .popup_cont

Both of those, or something similar, should work.

**Comment by dustindong** [comment]
Hey todd,

forgot to thank you for the help. thank you so much!

Dustin
