### ISSUE TITLE
Access to the parent element

### ISSUE THREAD

**Issue by nobe4** [Toddish/Popup#14]
Hello,
Great plugin, thanks for developping it ! :) 
I'm using it on a small project and I wanted to know how you can pass the original window element to the popup ? 

The use-case is the following : 
I have a main page `M` with a link `L`
When I click on the link the popup `P` shows
In `P` there is a redirect link `R`
When I click on `R` the popup close and `M` gets redirected on another url

I wasn't able to achieve this effet, and I started to pass the original window argument to set a new location but I wasn't able to do anything good.

Do you have any idea ? 
Thanks :)

**Comment by Toddish** [comment]
Is this all in the same window? I'm a little confused about the set up.

If you're opening an iframe in the popup (which I presume is this plugin), then try setting the target to the redirect as 'top'.

If this is all in a new window (in which case, I don't see how the plugin is being used), try using 'opener.location.href'.

I might have completely misunderstood though!

**Comment by nobe4** [comment]
Yes, all in the same windows, the popup open another page.
 I'll try this and let you know, thanks :)

**Comment by Toddish** [comment]
Awesome, glad you got it sorted :D
